version: "3.7"

services:
  nginx-cont:
    build: ./nginx/
    networks:
      - net-nginx
      - net-php
    expose:
      - 443
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env_secret
      - .env_config
    volumes:
      -  ${HOME}/data/wordpress:/${VOL_WP_PATH}
    depends_on:
     - wordpress-cont

  db-cont:
    build: ./database
    restart: always
    expose:
      - 3306
    networks:
      - net-php
      - net-db
    env_file:
      - .env_secret
      - .env_config
    volumes:
      -  ${HOME}/data/mariadb:${VOL_DB_PATH}

  wordpress-cont:
    build: ./wordpress
    restart: always
    expose:
      - 9000
    networks:
      - net-php
      - net-db
    env_file:
      - .env_secret
      - .env_config
    volumes:
      -  ${HOME}/data/wordpress:${VOL_WP_PATH}
    depends_on:
      - db-conts


networks:
  net-nginx:
    driver: bridge
  net-php:
    driver: bridge
    internal: true
  net-db:
    driver: bridge
    internal: true
