version: "3.7"

services:

  nginx-cont:
    build: ./nginx/
    networks:
      - intra
    ports:
      - "443:443"
    restart: always

  db-cont:
    build: ./database
    restart: always

  php-cont:
    build: ./wordpress
    restart: always

networks:
  intra:
    internal: true
