version: "3.7"

services:
  nginx-cont:
    build: ./nginx/
    networks:
      - net-nginx
      - net-php
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env_config
    volumes:
      - wordpress-vol:/${VOL_WP_PATH}

  db-cont:
    build: ./database
    restart: always
    expose:
      - 3306
    networks:
      - net-php
      - net-db
    env_file:
      - ./database/.env_mysql_config
    volumes:
      - db-vol:${VOL_DB_PATH}

  wordpress-cont:
    build: ./wordpress
    restart: always
    expose:
      - 9000
    networks:
      - net-php
      - net-db
    env_file:
      - .env_config
      - ./wordpress/.env_wp_config
    volumes:
      - wordpress-vol:${VOL_WP_PATH}

volumes:
  wordpress-vol:
  db-vol:


networks:
  net-nginx:
    driver: bridge
  net-php:
    driver: bridge
    internal: true
  net-db:
    driver: bridge
    internal: true
