version: "3.7"

services:

  nginx-cont:
    build: ./nginx/
    networks:
      - net-nginx
      - net-php
    ports:
      - "443:443"
    restart: always

  db-cont:
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  php-cont:
    build: ./wordpress
    restart: always

networks:
  net-nginx:
    driver: bridge
  net-php:
    driver: overlay
  net-db:
    driver: overlay

