version: "3.7"

services:

  nginx:
    build: ./nginx/
    networks:
      - intra
    ports:
      - "443:443"
    restart: always

  database:
    build: ./database
    restart: always

  wordpress:
    build: ./wordpress
    restart: always

networks:
  intra:
    driver: host
    internal: true
